### ISSUE TITLE
Fails for devices other then EFM32GG990F1024

### ISSUE THREAD

**Issue by Brando753** [ryankurte/efm32-base#1]
I tried using this to work with a EFM32G890F128 but for all other chips it will simply say 

```
efm32-base/device/EFM32G/Source/system_efm32g.c:34:23: fatal error: em_device.h: No such file or directory
 #include "em_device.h"
                       ^
compilation terminated.
```

This will happen for all chips besides the EFM32GG990F1024, The instructions say you just have to change the device name, is this a bug or is there a missing step? Seems like the probelm is in the device/device.cmake on how it includes other  family header files.

**Comment by Brando753** [comment]
Well at least its something simple, the EFM32GG directories include uses a lower case 'i' while all the others use a capitol 'I' adding another "include_directories(${CMAKE_CURRENT_LIST_DIR}/${CPU_FAMILY_U}/Include)" into the device.cmake file will let it build for all chips.

**Comment by ryankurte** [comment]
Oops. Looks like it should be devices/EFM32GG/Include, and entry in the devices/device.cmake file should be capitalised. Never picked it up in case insensitive OSX.
Sorry that took a while to look at, should be fixed now.
