### ISSUE TITLE
Updating to 5.13.X

### ISSUE THREAD

**Issue by ravnicas** [ryankurte/efm32-base#25]
Hello guys, i tried to update to 5.13.X by myself and kinda run into problems linking bluetooth enabled projects.

I've uploaded the whole SDK with my changes to [my repo](https://github.com/ravnicas/gecko_sdk/tree/master) and would like to contribute at least to updates of the sdk. I also would appriciate some help fixing the CMake files, especially the bluetooth part if this is possible.

Within the repo a simple "soc-empty" project from the SDK is included to try and test the compilation.

**Comment by KJ7LNW** [comment]
@ravnicas , @ryankurte , was this ever merged?  I thought 5.8 was the current SDK release.

```
efm32-base]$ git grep '5\.13'
<empty>
```
